### ISSUE TITLE
In Common Field prop disabled don't work.

### ISSUE THREAD

**Issue by SpringSan** [AbdullahQureshi1080/superforms-rn#13]
**Describe the bug**
I follow the example. The prop disabled is true. But I can input in this field.

**To Reproduce**
`<FormField
                    name="fullName"
                    label="Full Name"
                    disabled={true}
                  />`
**Expected behavior**

**Screenshots**
![微信图片_20221114131849](https://user-images.githubusercontent.com/22851482/201581309-58b33f56-93f0-436c-8ef9-f32f03fb2216.jpg)

**Smartphone (please complete the following information):**
 - Android

**Additional context**

**Comment by AbdullahQureshi1080** [comment]
@SpringSan Can you tell me which version you're using? Is it the latest?

**Comment by SpringSan** [comment]
"react": "18.1.0",
 "react-native": "0.70.2",
 "@superforms/superforms-rn": "^1.1.0",

**Comment by AbdullahQureshi1080** [comment]
@SpringSan will look into the issue as soon as I find some time, a quick thing you can try is to use the `editable={false}` on the `<FormField editable={false}/>`component and see if that helps.

**Comment by SpringSan** [comment]
🤝
