### ISSUE TITLE
FormDateSelector change by the model bind

### ISSUE THREAD

**Issue by SpringSan** [AbdullahQureshi1080/superforms-rn#16]
**Describe the bug**
When my data from api change but the value which the field show is not change. So i want to know how to change the value the field show except press the date selector. Also i bind the property 'date' to the state, the date selector change the date but it can't show in the field. Please help me , thank you.
   ''
**To Reproduce**
1. Get data from api

**Expected behavior**
The date field value can change by value change.

**Screens
![f146515abb93ae534c68cda1605328e](https://user-images.githubusercontent.com/22851482/209293766-fc9b7e98-a365-4102-9d97-4308fa762b1b.jpg)
hots**

**Smartphone (please complete the following information):**
 - OS: Andriod
 - React-Native Version 0.70.1
**Additional context**

**Comment by SpringSan** [comment]
I see other field have the Property 'value'

**Comment by AbdullahQureshi1080** [comment]
@SpringSan That's an interesting bug, while the form state is not meant to be directly manipulated by providing the value, it exists to be handled by form field state change. 

I can however try to add additional state updater binding that to the value prop and updating form state internally.

What you can do is instead of just having date object as a state variable, have the entire intial form values as the state and then when data from API changes try to update the initial values and see if that updates your date field. 

Let me know if that works. 

I will try to test the usecase whenever I can spare some free time this weekend.

**Comment by SpringSan** [comment]
Your suggestion that update the initial values i have tried. It don't works. But if you update the initial values the date selector's value will update, however the field value that show never change.  Also i think the function  'setFeildValue' can update the field value.
<img width="622" alt="1671881216156" src="https://user-images.githubusercontent.com/22851482/209433871-3d526028-faf7-4987-b843-0b92698e7e6b.png">

**Comment by SpringSan** [comment]
And the function onDateChange can't work

**Comment by AbdullahQureshi1080** [comment]
@SpringSan  Yes, I get the point. That is only changing the values for submission and not updating the base date picker's value, hence not the updated value in UI. What we could do is that If an existing value exists from the values[name] == name (date picker) as an initial value we can update that from the start or whenever values[name] for date changes. Kind of like an initial setter and onChange trigger.

**Comment by AbdullahQureshi1080** [comment]
```
  useEffect(() => {
    if (values[name] && moment(values[name).isValid()) {
      setFieldValue(name,date);
    }
  }, []);

```

@SpringSan Something like this, which might not be the best solution at the moment can make things work.

**Comment by SpringSan** [comment]
> ```
>   useEffect(() => {
>     if (values[name] && moment(values[name).isValid()) {
>       setFieldValue(name, values[name]);
>     }
>   }, []);
> ```
> 
> @SpringSan Something like this, which might not be the best solution at the moment can make things work.

Hey，I try to add the code to \node_modules\@superforms\superforms-rn\src\Form\FormDateSelector , but it doesn't works. And it seems never go into this code.

**Comment by AbdullahQureshi1080** [comment]
> > ```
> >   useEffect(() => {
> >     if (values[name] && moment(values[name).isValid()) {
> >       setFieldValue(name, values[name]);
> >     }
> >   }, []);
> > ```
> > 
> > @SpringSan Something like this, which might not be the best solution at the moment can make things work.
> 
> Hey，I try to add the code to \node_modules\@superforms\superforms-rn\src\Form\FormDateSelector , but it doesn't works. And it seems never go into this code.  

Hmm, it should have. I will debug this later in the week. Maybe you can add '''values [name]''' in the dependency array.

**Comment by SpringSan** [comment]
Ok . Thanks a lot
